---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homework-5 # Перезаписываем уже существующий ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://auth-service.default.svc.cluster.local/login
    nginx.ingress.kubernetes.io/auth-response-headers: x-auth-token
spec:
  rules:
    - http:
        paths:
          - path: / # Направляем все запросы к echoserver
            pathType: Prefix
            backend:
              service:
                name: homework-5
                port:
                  number: 80