---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    app: auth-service
  ports:
    - port: 80
      name: http
      targetPort: http
