---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hw-apigtw-helm.fullname" . }}
  namespace: default
  labels:
      app: auth-service
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: auth-service
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
          imagePullPolicy: {{ .Values.gateway.image.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.gateway.containerPort }}
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: homework-5-config
                  key: NODE_ENV
            - name: DATABASE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: homework-5-secret
                  key: DATABASE_URI
